### ISSUE TITLE
Inconsistent file names

### ISSUE THREAD

**Issue by glatard** [LivingPark-MRI/ppmi-scraper#36]
Some files need to be requested with a different name as the name of the downloaded file.

Example:
* requested file: `'Montreal_Cognitive_Assessment_MoCA.csv'`
* downloaded file: `Montreal_Cognitive_Assessment__MoCA_.csv`

This is an issue because the notebooks will keep re-downloading these files as the requested names are not found.

It could be solved by restoring the previous JSON object and populating it with the downloaded file names.

@yohanchatelain would you have time to look at this issue?

**Comment by yohanchatelain** [comment]
No, @mathdugre told me about that. I'll have a look.
