### ISSUE TITLE
Inconsistent file name in study files download

### ISSUE THREAD

**Issue by glatard** [LivingPark-MRI/ppmi-scraper#43]
The file called "Consensus APOE SNPs and GBA and LRRK2 Coding Variant Summary" in the PPMI study files is downloaded as "iu_genetic_consensus_20220310.csv", which makes the PPMI downloader download it even if it already exists. 

There are other, more minor inconsistencies involving '_' characters.

@yohanchatelain would you like to think of a way to address such inconsistencies? We could have a default name matching rule (the one already implemented) and have a table for special cases.

**Comment by yohanchatelain** [comment]
Solution proposal by @glatard:
- Keep a mapping between the `guessed name` (guessed from the web page) and the `real name` (actually downloaded)
- Try finding the guessed name and look for the real name if not
