### ISSUE TITLE
Version numbers in project definition

### ISSUE THREAD

**Issue by glatard** [LivingPark-MRI/ppmi-scraper#45]
Package versions are specified in project definition:
https://github.com/LivingPark-MRI/ppmi-scraper/blob/03435b84d499c78d232a5f1004454c8aa18548c9/pyproject.toml#L17
Installation of libxml2-4.8.0 breaks in my environment while latest version works. Is there a good reason to specify version numbers? If not let's remove them.

@mathdugre @mohanadarafe

**Comment by mathdugre** [comment]
@glatard, I don't think that freezing dependencies for libraries makes as much sense as for production applications.
I'm for removing the dependency pins in the `pyproject.toml` file.

**Comment by yohanchatelain** [comment]
No, I fixed them to avoid API change surprises, but we can remove them.
